### ISSUE TITLE
Unicode string length in ruby 1.9

### ISSUE THREAD

**Issue by quaternion** [blatyo/bencodr#2]
In ruby 1.9 length of utf-8 string is equal to the number of characters, not the number of bytes. Non-ASCII characters are encoded 2-6 bytes. For fix replace "length" to "bytesize" in file "bencodr/lib/bencodr/string.rb" line 14:

```
[string.length, ':', string].join
```

replace to:

```
[string.bytesize, ':', string].join
```

String#bytesize is works in ruby 1.8 and 1.9.

**Comment by blatyo** [comment]
Thanks for noticing the issue. I'm currently looking into what changes need to happen for decoding as well as encoding.
