### ISSUE TITLE
too big number for repeat range

### ISSUE THREAD

**Issue by Tarang** [blatyo/bencodr#5]
Sometimes with torrents I get this error

too big number for repeat range: /.{133400}/m
~/.rvm/gems/ruby-1.9.3-p125/gems/bencodr-3.0.1/lib/bencodr/parser.rb:40:in `parse_string'

How would I be able to solve this?

**Comment by blatyo** [comment]
This looks like a limitation of regular expressions. One way to solve this would be to not use `scan` with a regular expression, but `peek` with the length of the string. If you were to use `peek` though, you would have to advance the pointer.

**Comment by blatyo** [comment]
Hey @Tarangp, 3.0.2 is out and includes the fix to this issue. Thanks for your contributions and sorry it's taken me so long to get around to it.
