### ISSUE TITLE
Specific torrent ::DecodeError

### ISSUE THREAD

**Issue by rafapolo** [blatyo/bencodr#8]
Hello,
I've been working with bencodr for some weeks parsing and re-encoding 15.000 torrent files for a specific project. 

However, one torrent file - just one - gives me a 
BEncode::DecodeError: BEncode::DecodeError 
decode.rb:46:in `bdecode'

It is a correctly encoded torrent file because I can open it with other torrent applications, such as Transmission.

I could not fix the bencodr by myself but I think this file is a good case for make this lib 100%, after being considered stable for years.

The "special" torrent file is uploaded to http://extrapolo.com/download/7305.torrent

I appreciate any help.

**Comment by blatyo** [comment]
The error you having isn't with this gem. You want: https://github.com/dasch/ruby-bencode

That said, replacing that gem with this one could solve your issues.
